import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// One autogenerated sidebar over the docs tree: adding a file is adding
// a page — the structure comes from folders and front matter.
const sidebars: SidebarsConfig = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
